# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CI_CD_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppCenter
  pod 'AppCenter'

end
