# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # Codesigning identity for the application
  codesign_identity = "Apple Distribution: Gaurav Thakur (SYNZ9ZQLS2)" 

  # AppCenter Attributes
  appcenter_owner = "anshubansal-vwku"
  appcenter_app_name = "CI-CD-Demo"
  appcenter_api_token = "c4221d9ff4efc3ebfc467359af57a49d2185723e"

  # Teams webhook URL
  teams_webhook_url = "https://outlook.office.com/webhook/f6022cdd-331f-4073-977c-0be051526fec@36da45f1-dd2c-4d1f-af13-5abe46b99921/IncomingWebhook/54e278d40b1b4d2cb1f9587194ed55b4/8a621c5c-e7d1-40ab-be8a-cf0a5a1d8494"

  ## ====== ##
  desc "This lane build the application and publishes code on App Center"
  lane :beta do

    # Publish Mac Notification
    notification(subtitle: "Fastlane Job Started", message: "All Hail Build God!!")

    # Update build number
    updated_build_number = update_build_number
    puts updated_build_number

    # Get current system time and updated build name
    current_time = Time.new.strftime('%Y.%m.%d_%H.%M')
    build_name = "CI_CD_Demo_b_"+updated_build_number.to_s+"_"+current_time
    puts build_name

    # Build project adnd package IPA
    make_build(
      config: "Debug", 
      build_name: build_name
    )

    # Publish Mac Notification
    notification(subtitle: "Finished Building", message: "Uploading now...")

    # Pull changelog from Git
    changelog_git

    # Distribute IPA on AppCenter
    upload_build(
      build_name: build_name,
      changelog: lane_context[SharedValues::FL_CHANGELOG]
    )

    # Publish Mac Notification
    notification(subtitle: "Finished Uploading", message: "House-keeping...")

    # Notify teams about published build
    publish_on_teams(
      build_name: build_name,
      build_number: updated_build_number,
      date_time: current_time
    )

    # Commit version Bump
    commit_version_bump

    # Add Git Tag
    add_git_tag(
      grouping: "fastlane-builds",
      prefix: "b",
      build_number: updated_build_number
    )

    # Publish Mac Notification
    notification(subtitle: "Fastlane Job Finished", message: "All Done!!")

  end
  ## ====== ##

  ## ====== ##
  desc "This lane will update the build number of project"
  private_lane :update_build_number do
    increment_build_number
  end
  ## ====== ##

  ## ====== ##
  desc "This lane will build application with the provided confiuration"
  lane :make_build do |options|

    # Build app (If you are using Automaic Profile Management in Xcode then no need to add code-signing)
    build_app(
      scheme: "CI_CD_Demo",
      workspace: "CI_CD_Demo.xcworkspace",    # Use only if building a workspace
      clean: true,
      configuration: options[:config],
      include_bitcode: false,
      codesigning_identity: codesign_identity,
      export_method: "ad-hoc", 
      output_name: options[:build_name]
    )

    puts lane_context[SharedValues::IPA_OUTPUT_PATH]
    puts lane_context[SharedValues::DSYM_OUTPUT_PATH]
    puts lane_context[SharedValues::XCODEBUILD_ARCHIVE]
  end
  ## ====== ##

  ## ====== ##
  desc "This lane will upload build on AppCenter"
  lane :upload_build do |options|

    appcenter_upload(
      api_token: appcenter_api_token,
      owner_name: appcenter_owner,
      app_name: appcenter_app_name,
      file: options[:build_name]+".ipa",
      dsym: options[:build_name]+".app.dSYM.zip",
      release_notes: options[:changelog],
      notify_testers: true
    )

    puts lane_context[SharedValues::APPCENTER_BUILD_INFORMATION]
    puts lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK]
  end
  ## ====== ##

  ## ====== ##
  desc "Lane to get changelog from Git commits"
  lane :changelog_git do
    last_tag = last_git_tag

    if last_tag != nil
      changelog_from_git_commits(
        between: [last_tag, "HEAD"]
      )
    else 
      last_commit = last_git_commit
      changelog_from_git_commits(
        commits_count: 1
      )
    end

    puts lane_context[SharedValues::FL_CHANGELOG]
  end
  ## ====== ##

  ## ====== ##
  desc "Lane to publish notification on MS Teams"
  lane :publish_on_teams do |options|
    
    teams_facts = [
      {
        "name"=>"Build Name",
        "value"=>options[:build_name]
      },
      {
        "name"=>"Build Number",
        "value"=>options[:build_number]
      },
      {
        "name"=>"Date / Time",
        "value"=>options[:date_time]
      },
      {
        "name"=>"Download It Here",
        "value"=>lane_context[SharedValues::APPCENTER_BUILD_INFORMATION]['install_url']
      }
    ]

    teams(title: "New Build Available",
          message: "New build is published on AppCenter. Please download it on device to start testing.",
          facts: teams_facts,
          teams_url: teams_webhook_url)

  end
  ## ====== ##

end

